### ISSUE TITLE
Set up Github pages

### ISSUE THREAD

**Issue by bgyori** [WorldModelers/WorldModelers#4]
I think it would be nice to enable Github pages for this repo. This would basically allow us to render the README.md and link to any other relevant md pages we might later add to the repo in the form of a website. I think the address under default settings would be something like worldmodelers.github.io/corpusingestionandassembly. Any thoughts on whether this is a good idea? If we agree, I can set this up.

**Comment by kwalcock** [comment]
Lest anyone think they are working in a vacuum...

It sounds OK to me.  I'd be sure to put a link to the gh-pages URL in the main readme file so that people (e.g., me) realize it's there.  Sometimes an in between solution is to use a Wiki.

As more people fill in the information in the readme file and have difficulty describing the situation in the foreseen slots, it might become more clear what kind of additional functionality is needed.

**Comment by kwalcock** [comment]
This may not be quite the same thing, but jekyll templates are being processed to https://worldmodelers.com/CorpusIngestionAndAssembly/.  Note that they are being generated from the documentation branch.  That's just so that some rough drafts can be made without affecting the main branch.

**Comment by kwalcock** [comment]
I think this issue has largely been addressed.  It can always be reopened if not.
